Update Build and Deploy.yaml

diff --git a/.github/workflows/Build and Deploy.yaml b/.github/workflows/Build and Deploy.yaml
--- a/.github/workflows/Build and Deploy.yaml
+++ b/.github/workflows/Build and Deploy.yaml
@@ -24,7 +24,6 @@ jobs:
     runs-on: [self-hosted, linux, X64]
     outputs:
       runDeploy: ${{ steps.createPackage.outputs.deploy }}
-    
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
@@ -49,6 +48,40 @@ jobs:
           GITUsername=${{ github.repository_owner }}
           GITUseremail=${{ vars.EMAIL }}
           CodeFolderXML=${{ vars.CODEFOLDER }}
+
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            funcTest=0
+            sampleProc=0
+            compCount=1
+            
+            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
+            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
+            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
+            compNotes=$(grep '^buildNotes=' $file | cut -f2 -d'=')
+            deployPackage=$(grep '^deploy=' $file | cut -f2 -d'=')
+
+            compCount=$(echo "$compId" | awk -F "," '{print NF-1}')
+            compCount=$((compCount + 1))
+            #echo number of Components: $compCount
+            
+            export WD=${GITHUB_WORKSPACE}/cli/scripts/
+            export WORKSPACE=${GITHUB_WORKSPACE}/cli/scripts/
+            export GITHUB_WORKSPACE
+
+            find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
+
+            #chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
+            #chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            #chmod +x "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh"
+
+            source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
+            source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+
+            for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
+              _compId=$(echo $compId | cut -f $_compIdx -d",")
+              "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh" componentId=$_compId packageVersion=$compVer componentType=$compType notes="$compNotes" extractComponentXmlFolder="$CodeFolderXML"
+            done
+          done
 
           #Dev is already set
           deployPackageHWM=5
@@ -107,7 +140,6 @@ jobs:
             funcTest=0
             compCount=1
             postmanInst=0
-
             perfTest=0
 
             devEnvUpd=$(grep '^devEnvUpd=' $file | cut -f2 -d'=')
@@ -148,7 +180,115 @@ jobs:
                source "${GITHUB_WORKSPACE}/cli/scripts/bin/updateExtensions.sh" environmentId="$_devEnvId" componentId="$_devEnvConnId" componentType="$_devEnvCompType" fieldVal="$_pass"
             fi
 
-            #
+            envName="1.Dev"
+            for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
+              _compId=$(echo $compId | cut -f $_compIdx -d",")
+              "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$_compId packageVersion=$compVer componentType=$compType notes="$compNotes" env=$envName listenerStatus=$listenerStatus
+            done
+          done
+
+  deploytoTest:
+    runs-on: [self-hosted, linux, X64]
+    needs: [createPackage, deploytoDev]
+    environment:
+      name: "Test"
+    if: needs.createPackage.outputs.runDeploy <= 3
+    steps:
+      - uses: actions/checkout@v3
+      
+      - name: Changed Files
+        id: changed-files
+        uses: tj-actions/changed-files@v37.5.2
+        
+      # Runs a set of commands using the runners shell
+      - name: Deploy Package
+        run: |
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiUsername=${{ vars.BOOMI_USERNAME }}
+          API=${{ secrets.API }}
+          RepoURL=${{ github.server_url }}
+          RepoName=${{ github.repository }}
+          RepoPath=${RepoURL}/${RepoName}
+          GITUsername=${{ github.repository_owner }}
+          GITUseremail=${{ vars.EMAIL }}
+          CodeFolderXML=${{ vars.CODEFOLDER }}
+          POSTMAN=${{ secrets.POSTMAN }}  
+          
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            funcTest=0
+            
+            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
+            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
+            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
+            envName=$(grep '^deploy=' $file | cut -f2 -d'=')
+            listenerStatus=$(grep '^listenerStatus=' $file | cut -f2 -d'=')
+            compNotes=$(grep '^deployNotes=' $file | cut -f2 -d'=')
+            
+            sampleProc=$(grep '^sample=' $file | cut -f2 -d'=')
+            collectionId=$(grep '^collectionId=' $file | cut -f2 -d'=')
+            testId=$(grep '^testId=' $file | cut -f2 -d'=')
+          
+            export WD=${GITHUB_WORKSPACE}/cli/scripts/
+            export WORKSPACE=${GITHUB_WORKSPACE}/cli/scripts/
+            export GITHUB_WORKSPACE
+
+            find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
+
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
+            chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh"
+
+            source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
+            source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            
+            envName="2.Test"
+            "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$compId packageVersion=$compVer componentType=$compType notes="$compNotes" env=$envName listenerStatus=$listenerStatus
+
+            #_id=$RANDOM
+            _id=${{ env.ID }}
+            echo random: $_id
+            
+            _timeOut=${{ vars.TIMEOUT }}
+            if [[ $_timeOut == 0 ]]
+            then
+              echo need to set timeout
+              _timeOut=30
+            fi
+
+            if [[ $sampleProc == 1 ]]
+            then
+              echo Sampling Proc...
+              "${GITHUB_WORKSPACE}/cli/scripts/sampleProc.sh" $_timeOut $_id&
+            fi
+
+            if [[ $postmanInst == 0  && $funcTest == 1 ]]
+            then
+              curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
+              /usr/local/bin/postman login --with-api-key $POSTMAN
+              postmanInst=1
+            fi
+
+            if [ $funcTest == 1 ]
+            then
+              echo Sleeping...
+              sleep 15
+              echo Running Postman Collection
+              /usr/local/bin/postman collection run "$collectionId" -i "$testId" > /tmp/$collectionId.$testId.out
+              sed -i 's/\[90m//g ; s/\[30m//g' /tmp/$collectionId.$testId.out
+              postmanResult=$(grep assertions /tmp/post.out|tr -s ' ' '|' | awk -F "|" '{ print $6 }')
+              #postmanResult=$(echo $postmanOut | grep '200 OK' | wc -l)
+              echo output: $postmanResult
+              if [ "$postmanResult" == 0 ]
+              then
+                echo "Postman test OK"
+              elif [ "$postmanResult" == 1 ]
+              then
+                echo "Postman test failed"
+                exit 1
+              fi
+            fi
+
             perfTest=$(grep '^perfTest=' $file | cut -f2 -d'=')
             if [[ $perfTest == 1 ]]
             then
@@ -180,37 +320,75 @@ jobs:
               
               rm /tmp/jmeter.tgz
             fi
-
-            if [[ $postmanInst == 0  && $funcTest == 1 ]]
-            then
-              curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
-              /usr/local/bin/postman login --with-api-key $POSTMAN
-              postmanInst=1
-            fi
-            
-            #envName="1.Dev"
-            #for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
-            #  _compId=$(echo $compId | cut -f $_compIdx -d",")
-            #  "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$_compId packageVersion=$compVer componentType=$compType notes="$compNotes" env=$envName listenerStatus=$listenerStatus
-            #done
-
-            if [ $funcTest == 1 ]
-            then
-              echo Sleeping...
-              sleep 15
-              echo Running Postman Collection
-              /usr/local/bin/postman collection run "$collectionId" -i "$testId" > /tmp/$collectionId.$testId.out
-              sed -i 's/\[90m//g ; s/\[30m//g' /tmp/$collectionId.$testId.out
-              postmanResult=$(grep assertions /tmp/post.out|tr -s ' ' '|' | awk -F "|" '{ print $6 }')
-              #postmanResult=$(echo $postmanOut | grep '200 OK' | wc -l)
-              echo output: $postmanResult
-              if [ "$postmanResult" == 0 ]
-              then
-                echo "Postman test OK"
-              elif [ "$postmanResult" == 1 ]
-              then
-                echo "Postman test failed"
-                exit 1
-              fi
-            fi
+              
+            #we run spark separately because the `timeout` command terminates the script
+            #spark < /tmp/$_id.sample > /tmp/$_id.sample.out
+            #cat /tmp/$_id.sample
+            #cat /tmp/$_id.sample.out
+            #sample=1
           done
+
+      #- name: System Usage
+      #  run: |
+      #    _timeOut=30
+      #    if [[ $sample == 1 ]]
+      #    then
+       #       echo Sampling Proc...
+       #       "${GITHUB_WORKSPACE}/cli/scripts/sampleProc.sh" $_timeOut $ID
+       #       sample=1
+       #   fi
+
+  deploytoProd:
+    runs-on: [self-hosted, linux, X64]
+    needs: [createPackage, deploytoDev, deploytoTest]
+    environment:
+      name: "Prod"
+    if: needs.createPackage.outputs.runDeploy <= 1
+    steps:
+      - uses: actions/checkout@v3
+    
+      - name: Changed Files
+        id: changed-files
+        uses: tj-actions/changed-files@v37.5.2
+        
+      # Runs a set of commands using the runners shell
+      - name: Deploy Package
+        run: |
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiUsername=${{ vars.BOOMI_USERNAME }}
+          API=${{ secrets.API }}
+          RepoURL=${{ github.server_url }}
+          RepoName=${{ github.repository }}
+          RepoPath=${RepoURL}/${RepoName}
+          GITUsername=${{ github.repository_owner }}
+          GITUseremail=${{ vars.EMAIL }}
+          CodeFolderXML=${{ vars.CODEFOLDER }}
+          
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            funcTest=0
+            
+            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
+            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
+            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
+            envName=$(grep '^deploy=' $file | cut -f2 -d'=')
+            listenerStatus=$(grep '^listenerStatus=' $file | cut -f2 -d'=')
+            compNotes=$(grep '^deployNotes=' $file | cut -f2 -d'=')
+            
+            export WD=${GITHUB_WORKSPACE}/cli/scripts/
+            export WORKSPACE=${GITHUB_WORKSPACE}/cli/scripts/
+            export GITHUB_WORKSPACE
+
+            find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
+
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
+            chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh"
+
+            source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
+            source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+
+            envName="3.Prod"
+            "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$compId packageVersion=$compVer componentType=$compType notes="$compNotes" env=$envName listenerStatus=$listenerStatus
+          done
+          
