Update Build and Deploy.yaml

diff --git a/.github/workflows/Build and Deploy.yaml b/.github/workflows/Build and Deploy.yaml
--- a/.github/workflows/Build and Deploy.yaml
+++ b/.github/workflows/Build and Deploy.yaml
@@ -39,12 +39,359 @@ jobs:
         AWS_ACCESS_KEY_ID: ${{ secrets.ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.ID2 }}
       run:  |
-          sudo apt install jq
+          sudo apt-get install -y curl
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
           unzip -q /tmp/awscliv2.zip -d /tmp
           rm /tmp/awscliv2.zip
           sudo /tmp/aws/install --update
           rm -rf /tmp/aws/
 
-          _pass=$(aws secretsmanager get-secret-value --secret-id employees | jq -r ".SecretString" | awk -F ":" '{ print $2 }' | sed "s/^\"//g ; s/\"}//g")
-          echo $_pass
+createPackage:
+    runs-on: [self-hosted, linux, X64]
+    outputs:
+      runDeploy: ${{ steps.createPackage.outputs.deploy }}
+    
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+        #with:
+        #  fetch-depth: 0
+        #  path: INT-001
+      
+      - name: Changed Files
+        id: changed-files
+        uses: tj-actions/changed-files@v37.5.2
+
+      # Runs a set of commands using the runners shell
+      - name: Create Package
+        id: createPackage
+        run: |
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiUsername=${{ vars.BOOMI_USERNAME }}
+          API=${{ secrets.API }}
+          RepoURL=${{ github.server_url }}
+          RepoName=${{ github.repository }}
+          RepoPath=${RepoURL}/${RepoName}
+          GITUsername=${{ github.repository_owner }}
+          GITUseremail=${{ vars.EMAIL }}
+          CodeFolderXML=${{ vars.CODEFOLDER }}
+
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            funcTest=0
+            sampleProc=0
+            compCount=1
+            
+            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
+            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
+            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
+            compNotes=$(grep '^buildNotes=' $file | cut -f2 -d'=')
+            deployPackage=$(grep '^deploy=' $file | cut -f2 -d'=')
+
+            compCount=$(echo "$compId" | awk -F "," '{print NF-1}')
+            compCount=$((compCount + 1))
+            echo number of Components: $compCount
+            
+            export WD=${GITHUB_WORKSPACE}/cli/scripts/
+            export WORKSPACE=${GITHUB_WORKSPACE}/cli/scripts/
+            export GITHUB_WORKSPACE
+
+            find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
+
+            #chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
+            #chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            #chmod +x "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh"
+
+            source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
+            source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+
+            for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
+              _compId=$(echo $compId | cut -f $_compIdx -d",")
+              "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh" componentId=$_compId packageVersion=$compVer componentType=$compType notes="$compNotes" extractComponentXmlFolder="$CodeFolderXML"
+            done
+          done
+
+          #Dev is already set
+          deployPackageHWM=5
+          
+          if [ $deployPackage == "2.Test" ]
+          then
+            deployPackageHWM=3
+          elif [ $deployPackage == "3.Prod" ]
+          then
+            deployPackageHWM=1
+          fi
+
+          echo "deploy=$deployPackageHWM" >> "$GITHUB_OUTPUT"
+
+  deploytoDev:
+    runs-on: [self-hosted, linux, X64]
+    needs: createPackage
+    #if: contains('1.Dev',needs.createPackage.outputs.runDeploy)
+    if: needs.createPackage.outputs.runDeploy <= 5
+    steps:
+      - uses: actions/checkout@v3
+        #with:
+        #  fetch-depth: 0
+        #  path: INT-001
+
+      - name: Changed Files
+        id: changed-files
+        uses: tj-actions/changed-files@v37.5.2
+        #with:
+        #  envTargetName: "1.Dev"
+        
+      # Runs a set of commands using the runners shell
+      - name: Deploy Package
+        run: |
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiUsername=${{ vars.BOOMI_USERNAME }}
+          API=${{ secrets.API }}
+          RepoURL=${{ github.server_url }}
+          RepoName=${{ github.repository }}
+          RepoPath=${RepoURL}/${RepoName}
+          GITUsername=${{ github.repository_owner }}
+          GITUseremail=${{ vars.EMAIL }}
+          CodeFolderXML=${{ vars.CODEFOLDER }}
+          POSTMAN=${{ secrets.POSTMAN }}
+          
+          postmanInst=0
+          
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            funcTest=0
+            compCount=1
+            
+            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
+            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
+            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
+            envName=$(grep '^deploy=' $file | cut -f2 -d'=')
+            listenerStatus=$(grep '^listenerStatus=' $file | cut -f2 -d'=')
+            compNotes=$(grep '^deployNotes=' $file | cut -f2 -d'=')
+            devEnvUpd=$(grep '^devEnvUpd=' $file | cut -f2 -d'=')
+            
+            collectionId=$(grep '^collectionId=' $file | cut -f2 -d'=')
+            testId=$(grep '^testId=' $file | cut -f2 -d'=')
+            funcTest=$(grep '^funcTest=' $file | cut -f2 -d'=')
+
+            compCount=$(echo "$compId" | awk -F "," '{print NF-1}')
+            compCount=$((compCount + 1))
+            echo number of Components: $compCount
+
+            export WD=${GITHUB_WORKSPACE}/cli/scripts/
+            export WORKSPACE=${GITHUB_WORKSPACE}/cli/scripts/
+            export GITHUB_WORKSPACE
+
+            if [[ $devEnvUpd == 1 ]]
+            then
+              _devEnvConnId=$(grep '^devEnvConnId=' $file | cut -f2 -d'=')
+              _devEnvConnName=$(grep '^devEnvConnName=' $file | cut -f2 -d'=')
+              _devEnvConnFieldId=$(grep '^devEnvConnFieldId=' $file | cut -f2 -d'=')
+              _devEnvSSMId=$(grep '^devEnvSSMId=' $file | cut -f2 -d'=')
+
+              _pass=$(aws secretsmanager get-secret-value --secret-id $_devEnvSSMId | jq -r ".SecretString" | awk -F ":" '{ print $2 }' | sed "s/^\"//g ; s/\"}//g")
+              source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
+            fi
+            
+            if [[ $postmanInst == 0  && $funcTest == 1 ]]
+            then
+              #curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
+              /usr/local/bin/postman login --with-api-key $POSTMAN
+              postmanInst=1
+            fi
+            
+            find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
+
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
+            chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh"
+
+            source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
+            source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+
+            envName="1.Dev"
+
+            for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
+              _compId=$(echo $compId | cut -f $_compIdx -d",")
+              "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$_compId packageVersion=$compVer componentType=$compType notes="$compNotes" env=$envName listenerStatus=$listenerStatus
+            done
+
+            if [ $funcTest == 1 ]
+            then
+              echo Sleeping...
+              sleep 15
+              echo Running Postman Collection
+              postmanOut=$(/usr/local/bin/postman collection run "$collectionId" -i "$testId")       
+              postmanResult=$(echo $postmanOut | grep '200 OK' | wc -l)
+              echo output: $postmanResult
+              if [ "$postmanResult" == 0 ]
+              then
+                  echo "::error Postman test failed"
+                  exit 1
+              elif [ "$postmanResult" == 1 ]
+              then
+                echo "Postman test OK"
+                exit 0
+              fi
+            fi
+          done
+
+  deploytoTest:
+    runs-on: [self-hosted, linux, X64]
+    needs: [createPackage, deploytoDev]
+    environment:
+      name: "Test"
+    if: needs.createPackage.outputs.runDeploy <= 3
+    steps:
+      - uses: actions/checkout@v3
+      
+      - name: Changed Files
+        id: changed-files
+        uses: tj-actions/changed-files@v37.5.2
+        
+      # Runs a set of commands using the runners shell
+      - name: Deploy Package
+        run: |
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiUsername=${{ vars.BOOMI_USERNAME }}
+          API=${{ secrets.API }}
+          RepoURL=${{ github.server_url }}
+          RepoName=${{ github.repository }}
+          RepoPath=${RepoURL}/${RepoName}
+          GITUsername=${{ github.repository_owner }}
+          GITUseremail=${{ vars.EMAIL }}
+          CodeFolderXML=${{ vars.CODEFOLDER }}
+          POSTMAN=${{ secrets.POSTMAN }}  
+          
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            funcTest=0
+            
+            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
+            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
+            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
+            envName=$(grep '^deploy=' $file | cut -f2 -d'=')
+            listenerStatus=$(grep '^listenerStatus=' $file | cut -f2 -d'=')
+            compNotes=$(grep '^deployNotes=' $file | cut -f2 -d'=')
+            
+            sampleProc=$(grep '^sample=' $file | cut -f2 -d'=')
+            collectionId=$(grep '^collectionId=' $file | cut -f2 -d'=')
+            testId=$(grep '^testId=' $file | cut -f2 -d'=')
+          
+            export WD=${GITHUB_WORKSPACE}/cli/scripts/
+            export WORKSPACE=${GITHUB_WORKSPACE}/cli/scripts/
+            export GITHUB_WORKSPACE
+
+            find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
+
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
+            chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh"
+
+            source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
+            source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            
+            envName="2.Test"
+            "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$compId packageVersion=$compVer componentType=$compType notes="$compNotes" env=$envName listenerStatus=$listenerStatus
+
+            #_id=$RANDOM
+            _id=${{ env.ID }}
+            echo random: $_id
+            
+            _timeOut=${{ vars.TIMEOUT }}
+            if [[ $_timeOut == 0 ]]
+            then
+              echo need to set timeout
+              _timeOut=30
+            fi
+
+            if [[ $sampleProc == 1 ]]
+            then
+              echo Sampling Proc...
+              "${GITHUB_WORKSPACE}/cli/scripts/sampleProc.sh" $_timeOut $_id&
+
+              echo Running Postman Collection
+              postmanOut=$(/usr/local/bin/postman collection run "$collectionId" -i "$testId")       
+              postmanResult=$(echo $postmanOut | grep '200 OK' | wc -l)
+              echo output: $postmanResult
+              if [ "$postmanResult" == 0 ]
+              then
+                  echo "::error Postman test failed"
+                  exit 1
+              elif [ "$postmanResult" == 1 ]
+              then
+                echo "Postman test OK"
+                #we run spark separately because the `timeout` command terminates the script
+                spark < /tmp/$_id.sample > /tmp/$_id.sample.out
+                cat /tmp/$_id.sample
+                cat /tmp/$_id.sample.out
+              fi
+            fi
+            sample=1              
+          done
+
+      #- name: System Usage
+      #  run: |
+      #    _timeOut=30
+      #    if [[ $sample == 1 ]]
+      #    then
+       #       echo Sampling Proc...
+       #       "${GITHUB_WORKSPACE}/cli/scripts/sampleProc.sh" $_timeOut $ID
+       #       sample=1
+       #   fi
+
+  deploytoProd:
+    runs-on: [self-hosted, linux, X64]
+    needs: [createPackage, deploytoDev, deploytoTest]
+    environment:
+      name: "Prod"
+    if: needs.createPackage.outputs.runDeploy <= 1
+    steps:
+      - uses: actions/checkout@v3
+        #with:
+        #  fetch-depth: 0
+        #  path: INT-001
+
+      - name: Changed Files
+        id: changed-files
+        uses: tj-actions/changed-files@v37.5.2
+        
+      # Runs a set of commands using the runners shell
+      - name: Deploy Package
+        run: |
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
+          BoomiUsername=${{ vars.BOOMI_USERNAME }}
+          API=${{ secrets.API }}
+          RepoURL=${{ github.server_url }}
+          RepoName=${{ github.repository }}
+          RepoPath=${RepoURL}/${RepoName}
+          GITUsername=${{ github.repository_owner }}
+          GITUseremail=${{ vars.EMAIL }}
+          CodeFolderXML=${{ vars.CODEFOLDER }}
+          
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            funcTest=0
+            
+            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
+            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
+            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
+            envName=$(grep '^deploy=' $file | cut -f2 -d'=')
+            listenerStatus=$(grep '^listenerStatus=' $file | cut -f2 -d'=')
+            compNotes=$(grep '^deployNotes=' $file | cut -f2 -d'=')
+            
+            export WD=${GITHUB_WORKSPACE}/cli/scripts/
+            export WORKSPACE=${GITHUB_WORKSPACE}/cli/scripts/
+            export GITHUB_WORKSPACE
+
+            find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
+
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
+            chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh"
+
+            source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
+            source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
+
+            envName="3.Prod"
+            "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$compId packageVersion=$compVer componentType=$compType notes="$compNotes" env=$envName listenerStatus=$listenerStatus
+          done
