Update CreatePackage.yaml

diff --git a/.github/workflows/CreatePackage.yaml b/.github/workflows/CreatePackage.yaml
--- a/.github/workflows/CreatePackage.yaml
+++ b/.github/workflows/CreatePackage.yaml
@@ -78,7 +78,7 @@ jobs:
             fi
             
             find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
-            #find ${GITHUB_WORKSPACE} -name *.sh -exec ls -ltr {} \;
+            find ${GITHUB_WORKSPACE} -name *.sh -exec ls -ltr {} \;
 
             chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
             chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
@@ -87,12 +87,11 @@ jobs:
             source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
             source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
 
-            #"${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh" componentId=$compId packageVersion=$compVer componentType=$compType notes="$compNotes" extractComponentXmlFolder="$CodeFolderXML"
+            "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh" componentId=$compId packageVersion=$compVer componentType=$compType notes="$compNotes" extractComponentXmlFolder="$CodeFolderXML"
 
             if [ $deployPackage == 1 ]
             then
-              echo Deploying
-              #"${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$compId packageVersion=$packageVersion componentType=$compType notes="$compNotes" env=$env listenerStatus=$listenerStatus
+              "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$compId packageVersion=$packageVersion componentType=$compType notes="$compNotes" env=$env listenerStatus=$listenerStatus
             fi
 
             if [ $funcTest == 1 ]
@@ -100,7 +99,15 @@ jobs:
               echo Running Postman Collection
               _postmanOut=$(/usr/local/bin/postman collection run "$collectionId" -i "$testId" | grep test-scripts | sed 's/  *//g')
               echo output: $_postmanOut
-              
-              #"${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$compId packageVersion=$packageVersion componentType=$compType notes="$compNotes" env=$env listenerStatus=$listenerStatus
+              _postmanResult=$(echo $_postmanOut | awk -F "|" { print $3 }')
+              if $_postmanResult != 1
+              then
+                  echo "::error Postman test failed"
+                  exit 1
+              elif $_postmanResult == 0
+              then
+                echo "Postman test OK"
+                exit 0
+              fi
             fi
           done
