Update CreatePackage.yaml

diff --git a/.github/workflows/CreatePackage.yaml b/.github/workflows/CreatePackage.yaml
--- a/.github/workflows/CreatePackage.yaml
+++ b/.github/workflows/CreatePackage.yaml
@@ -101,16 +101,17 @@ jobs:
               echo output: $postmanOut
               #postmanOut=$(/usr/local/bin/postman collection run "$collectionId" -i "$testId" | grep test-scripts | sed 's/  *//g')
               #postmanResult=$(echo $postmanOut | grep test-scripts | sed 's/ *//g' | awk -F "|" '{ print $3 }')
-              postmanResult=$(echo $postmanOut | grep test-scripts)
+              
+              postmanResult=$(echo $postmanOut | grep 'test-scripts │ 1' | wc -l)
               echo output: $postmanResult
-              #if [ "$postmanResult" != 1 ]
-              #then
-              #    echo "::error Postman test failed"
-              #    exit 1
-              #elif [ "$postmanResult" == "0" ]
-              #then
-              #  echo "Postman test OK"
-              #  exit 0
-              #fi
+              if [ "$postmanResult" == 0 ]
+              then
+                  echo "::error Postman test failed"
+                  exit 1
+              elif [ "$postmanResult" == 1 ]
+              then
+                echo "Postman test OK"
+                exit 0
+              fi
             fi
           done
